### ISSUE TITLE
Insect pathfinder flies into water

### ISSUE THREAD

**Issue by WenXin20** [itsmeow/betteranimalsplus#225]
**Describe the bug**
- Insects (butterflies & dragonflies) don't seem ever fly once they land on the ground, and they always land on the center of a block. They flap their wings if it rains, but are still stuck on the ground.
- Animals also don't try to escape or swim out of water. And they seem to rarely wander around or panic when punched.

**To Reproduce**
1. Spawn animals in water
2. Spawn insects on land
3. Observe

**Expected behavior**
- For animals to swim out of water and insects to fly around.

**Versions:**

- `Minecraft v1.16.4`
- `Forge v35.1.13`
- `Better Animals + v10.1.0`

**Comment by itsmeow** [comment]
Insects don't react to creative players. They will fly away if you are in survival. They will only move in rain if there is cover. If there is no cover, they do nothing and die. For simplicity's sake, yes they are supposed to land in the middle of a block.

What is "animals". Vanilla animals don't try to actively escape water either, this is expected. Many of our animals panic when punched, but not all of them. This is intentional.

The only real "bug" here is the insect pathfinder will fly into water.
