### ISSUE TITLE
Suggestion-ambiance mode

### ISSUE THREAD

**Issue by PurpleHel** [itsmeow/betteranimalsplus#239]
It'd be nice if the mod had an ambiance mode, where all the animals would be peaceful to mobs as well as the player. I don't want to play in peaceful, but I also don't want boars and lampreys killing everything. For now I've just disabled them from spawning, but I'd rather just be able to config the mod to ambiance mode and let them exist. I searched for 'peaceful' and 'ambiance' to see if this had been suggested before, and didn't see anything, but apologies if this has been suggested and rejected before.

**Comment by itsmeow** [comment]
We do have a peaceful/neutral to player mode that occurs on peaceful difficulty, but I also see how the inter-animal murder fest could be annoying. We have actually implemented a hunger system on most of the predatory animals, the exception to this is boars, since they're supposed to be literal hell-spawn within the context of the mod. I don't know how useful this would be now with our hunger system. I could possibly add a "nerf boars" option, since I do think they are quite overpowered, but that's intentional.

**Comment by dannydjdk** [comment]
Another potential alternative might be a config option to have boars use the predator hunger system. I personally find them to be too much of a nuisance to be fun, but they could be an interesting challenge if they weren't quite as much of a nuisance. I think the predator system has a much more realistic feel to it too.

**Comment by itsmeow** [comment]
I've addressed the boar issue a bit here: https://github.com/itsmeow/betteranimalsplus/commit/0ca24c990647772527a43af9d16d744af37b46c7
(download: https://github.com/itsmeow/betteranimalsplus/releases/tag/alpha-1.16.5-10.1.0.27)
Let me know if that properly addresses your concerns.

**Comment by dannydjdk** [comment]
I can't speak for the OP, but I love this! I should be able to find the perfect balance for my pack with these options.
Thank you!!!

**Comment by itsmeow** [comment]
I think this has been mostly addressed, so I'm going to close it. It's not exactly what OP requested but I think it works.

**Comment by PurpleHel** [comment]
I haven't had time to play in a while so dunno what the change is, but thanks for whatever you did :)

**Comment by itsmeow** [comment]
We've just added some config options to allow boars to be nerfed. It just released on CurseForge, but has been out in the alpha a few days.

**Comment by PurpleHel** [comment]
Cool, thanks again!
