### ISSUE TITLE
Uknown structure piece minecraft:bigdungeon - server overloading

### ISSUE THREAD

**Issue by JustThemo** [itsmeow/betteranimalsplus#240]
I'm not 100% sure whether it's a problem with just the mod or if it's having problems with Quark. Found similar issues on Quark's GitHub and found info that it's because it's colliding with BetterAnimalsPlus. My server is overloading pretty badly around the time when this message pops up in the console:

[Server thread/ERROR] [net.minecraft.world.gen.feature.structure.Structures/]: Unknown structure piece id: minecraft:bigdungeon

It happens multiple times in a single second. Not all the time but pretty often. I suppose it's because my friend is wandering around and trying to load this unknown structure by doing so.

Sometimes it just lags server side, one time we crashed with a 'java.lang.StackOverflowError' message.

**To Reproduce**
1. Have both Quark and BetterAnimalsPlus on
2. Walk around
3. Check the console

**Versions:**
 - Minecraft Version: 1.15.2
 - Forge Version: forge-1.15.2-31.2.45
 - Mod Version: 1.15.2-10.1.0

**Comment by itsmeow** [comment]
https://github.com/Vazkii/Quark/issues/2410
This issue is related to another crash we fixed, if you are referencing that. It's not related to the "Unknown structure" error.
Another one, here: https://github.com/Vazkii/Quark/issues/2567
States the error is "inoffensive", which I assume means it's more of warning (the game should function).

There is an open issue matching this: https://github.com/Vazkii/Quark/issues/2691
I would say this isn't related to BAP. I think it's more likely a coincendence (the log message doesn't mean anything by itself). Your server is likely just having general performance issues and also getting a lot of log messages from unknown structures. Maybe watch the open Quark issue, but that first one with BAP is a purely coincidental crash that occured AFTER your log error and somehow got reported to Quark.
