### ISSUE TITLE
Capes don't fit into Curio slots

### ISSUE THREAD

**Issue by ZeekDaGeek** [itsmeow/betteranimalsplus#246]
All of the capes, while claiming to be a Curio `Back` slot don't let you put them on if you're currently wearing something in your Vanilla chestplate slot. If you take the chestplate off you can put the Cape into your curio slot until you reconnect when it pops off again.

Better Animals Plus: v1.16.4-10.1.0

**Comment by itsmeow** [comment]
The issue related to this is a bit more nuanced and I'm aware of it! The issue is: You can't equip a cape into the Curios slot if anything is currently in your chest slot. This is a problem with the logic related to making sure you don't put a cape in both slots- it's incorrect, and instead stops you if *anything* is in the chest slot. So a workaround while I fix this is to take off your chestplate first!

**Comment by itsmeow** [comment]
Don't know how I failed to read your description. Yeah. Looks like you got it! I look like an idiot, lol. Thanks!
