### ISSUE TITLE
the miniboss's  skull shield and boss bone weapon 

### ISSUE THREAD

**Issue by MokoBlack** [itsmeow/betteranimalsplus#27]
the skull of the miniboss look so big wen wear on the head,  i think  it can use as a shield will be more good
and i guse  the bone weapon is on plan?  the antler spear and knife ?

**Comment by itsmeow** [comment]
No, we aren't planning bone weapons, and it doesn't really fit the overall idea (animals and flora). The reason it's so big is because it has to cover the head. The mob is also about that large as well when active at night, so when it is killed it's head would come off about that size (although probably larger).
I think the bone ideas are cool, but they don't fit.
Closing.
