### ISSUE TITLE
Feature Request: New types of animals

### ISSUE THREAD

**Issue by LidorPrototype** [itsmeow/betteranimalsplus#304]
I saw that many many mods (including this one) is missing animals like lions, rhinos, giraffes, zebras and more.

Do you have plans to add this type of animals (and possibly others) ?

**Comment by itsmeow** [comment]
The goal of this mod is not to add every type of animal, we try to keep Better Animals Plus in a foresty-esque theme alongside some additions that makes sense for the biome, plus some water creatures and a few fun additions. Rhinos, giraffes, etc are too niche and specific to certain areas in our opinion and also feel overdone in other mods - they're over-represented. There are more unique and awesome animals than this set of animals that seem to be so much media and entertainment. An example of a niche creature that we add is the Lammergeier - no other mod has included this fascinating animal, and it works because they're typically only in mountainous regions. We don't think adding lions, rhinos, giraffes, zebras, elephants, etc. would fit the theme of our mod. All of our planned features are on [Trello](https://trello.com/b/N9Zznyyf/better-animals-plus-minecraft-mod).

**Comment by LidorPrototype** [comment]
ok, thank you :)
I haven't saw a mod that adds lions, rhinos and more that suitable for 1.18.1 unfortunately
