### ISSUE TITLE
[FABRIC 1.17.1] vanilla Animals not spawning anymore 

### ISSUE THREAD

**Issue by MSandro** [itsmeow/betteranimalsplus#327]
## Describe the bug
I have added BetterAnimals Plus to my 1.17.1 Fabric Modpack named Sky FABRICation 2. Now I realized no animals are spawning on my server.
There are now no vanilla animals and BAP creatures are very very rare.
Could it be possible that the mod is changing some vanilla spawn behavour for Animals?

## To Reproduce
1. create a Void World (on a server with biome: plains)
2. build a large area of Grass Blocks
3. no Animals will spawn

## Expected behavior
Animals should spawn

## Screenshots
![image](https://user-images.githubusercontent.com/10937159/163954399-c9e1429c-1c0e-47bb-b5cb-ef26cfd38da0.png)

## Versions
 - Minecraft Version: 1.17.1
 - Architectury API Version: 2.10.6
 - Platform (Forge/Fabric): Fabric
  - Fabric Loader Version: 0.13.3
 - Fabric API Version: 0.46.1
 - Mod Version: 11.0.5

**Comment by itsmeow** [comment]
Hi, the way world spawns work, spawning only occurs in *newly generated chunks*. Vanilla acts the same way. Since you built this grass platform, any spawning that occurs is "repopulation" type spawning, which occurs extremely slowly. The lack of vanilla animals is likely pure probability (15 BAP animals vs 5 vanilla animals, so BAP is more likely to spawn).

This behavior is identical to vanilla aside from the fact that BAP is spawning in higher proportion by simple probability. If you were to create this without BAP, you would see the same amount of vanilla animals as you do BAP animals now.

A possible workaround for this would be reducing ALL BAP spawn weights to 1 in the configuration, this might give vanilla an equal shot.

**Comment by MSandro** [comment]
thanks, is there any way to configure BAP for my modpack? Because BAP can be configurable for each world, it is hard for modpack makers to pre-configure BAP.
maybe it would be nice to have an betteranimalsplus-server.json5 template in the config folder which would be copied to the serverconfig folder in the world directories. This would still allow to customize the mod for each world, but would allow modpack devs to customize the mod. Just as suggestion.

**Comment by itsmeow** [comment]
Please read the FAQ.
